name: release-image-build

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit reference (branch or SHA) from which to build the images.'
        required: true
      tag:
        description: 'Desired release version tag (e.g. v0.6.0-rc.0).'
        required: true

jobs:
  release_operator_image:
    env:
      working-directory: ./ray-operator
    name: Release Operator Docker Images
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commit }}

    - name: install kubebuilder
      run: |
        wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.0.0/kubebuilder_$(go env GOOS)_$(go env GOARCH)
        sudo mv kubebuilder_$(go env GOOS)_$(go env GOARCH) /usr/local/bin/kubebuilder

    - name: Get revision SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Get dependencies
      run: go mod download
      working-directory: ${{env.working-directory}}

    - name: Build
      run: make build
      working-directory: ${{env.working-directory}}

    - name: Test
      run: make test
      working-directory: ${{env.working-directory}}

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Build Docker Image - Operator
      run: |
        IMG=kuberay/operator:${{ steps.vars.outputs.sha_short }} make docker-image
      working-directory: ${{env.working-directory}}

    - name: Log in to Quay.io
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Push Operator to Quay.io
      run: |
        docker image tag kuberay/operator:${{ steps.vars.outputs.sha_short }} quay.io/kevin85421/kuberay:${{ steps.vars.outputs.sha_short }};
        docker push quay.io/kevin85421/kuberay:${{ steps.vars.outputs.sha_short }};
        docker image tag kuberay/operator:${{ steps.vars.outputs.sha_short }} quay.io/kevin85421/kuberay:${{ github.event.inputs.tag }};
        docker push quay.io/kevin85421/kuberay:${{ github.event.inputs.tag }}